# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'catkin_ws/src/ros_ocare_nav/rqt_ocare/resource/ocare_ui.ui'
#
# Created: Tue Jul 12 11:46:56 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_OcareGui(object):
    def setupUi(self, OcareGui):
        OcareGui.setObjectName(_fromUtf8("OcareGui"))
        OcareGui.resize(800, 600)
        self.gridLayoutWidget = QtGui.QWidget(OcareGui)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 30, 371, 401))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lcdNumberDiffMode = QtGui.QLCDNumber(self.gridLayoutWidget)
        self.lcdNumberDiffMode.setObjectName(_fromUtf8("lcdNumberDiffMode"))
        self.gridLayout.addWidget(self.lcdNumberDiffMode, 4, 1, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 8, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.graphicsViewOrient = QtGui.QGraphicsView(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsViewOrient.sizePolicy().hasHeightForWidth())
        self.graphicsViewOrient.setSizePolicy(sizePolicy)
        self.graphicsViewOrient.setMaximumSize(QtCore.QSize(100, 100))
        self.graphicsViewOrient.setSizeIncrement(QtCore.QSize(0, 0))
        self.graphicsViewOrient.setObjectName(_fromUtf8("graphicsViewOrient"))
        self.gridLayout.addWidget(self.graphicsViewOrient, 8, 1, 1, 1)
        self.pushButtonStart = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonStart.sizePolicy().hasHeightForWidth())
        self.pushButtonStart.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonStart.setFont(font)
        self.pushButtonStart.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButtonStart.setObjectName(_fromUtf8("pushButtonStart"))
        self.gridLayout.addWidget(self.pushButtonStart, 0, 1, 1, 1)
        self.checkBoxArmOpen = QtGui.QCheckBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxArmOpen.sizePolicy().hasHeightForWidth())
        self.checkBoxArmOpen.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBoxArmOpen.setFont(font)
        self.checkBoxArmOpen.setObjectName(_fromUtf8("checkBoxArmOpen"))
        self.gridLayout.addWidget(self.checkBoxArmOpen, 3, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 7, 0, 1, 1)
        self.lcdNumberDiffMode_2 = QtGui.QLCDNumber(self.gridLayoutWidget)
        self.lcdNumberDiffMode_2.setObjectName(_fromUtf8("lcdNumberDiffMode_2"))
        self.gridLayout.addWidget(self.lcdNumberDiffMode_2, 7, 1, 1, 1)
        self.label_5 = QtGui.QLabel(OcareGui)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 131, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayoutWidget_2 = QtGui.QWidget(OcareGui)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(470, 30, 305, 406))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.num_2 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_2.sizePolicy().hasHeightForWidth())
        self.num_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(45)
        font.setBold(False)
        font.setWeight(50)
        self.num_2.setFont(font)
        self.num_2.setObjectName(_fromUtf8("num_2"))
        self.gridLayout_2.addWidget(self.num_2, 2, 1, 1, 1)
        self.num_9 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_9.sizePolicy().hasHeightForWidth())
        self.num_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(45)
        font.setBold(False)
        font.setWeight(50)
        self.num_9.setFont(font)
        self.num_9.setObjectName(_fromUtf8("num_9"))
        self.gridLayout_2.addWidget(self.num_9, 0, 2, 1, 1)
        self.num_3 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_3.sizePolicy().hasHeightForWidth())
        self.num_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(45)
        font.setBold(False)
        font.setWeight(50)
        self.num_3.setFont(font)
        self.num_3.setObjectName(_fromUtf8("num_3"))
        self.gridLayout_2.addWidget(self.num_3, 2, 2, 1, 1)
        self.num_4 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_4.sizePolicy().hasHeightForWidth())
        self.num_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(45)
        font.setBold(False)
        font.setWeight(50)
        self.num_4.setFont(font)
        self.num_4.setObjectName(_fromUtf8("num_4"))
        self.gridLayout_2.addWidget(self.num_4, 1, 0, 1, 1)
        self.num_1 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_1.sizePolicy().hasHeightForWidth())
        self.num_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(45)
        font.setBold(False)
        font.setWeight(50)
        self.num_1.setFont(font)
        self.num_1.setObjectName(_fromUtf8("num_1"))
        self.gridLayout_2.addWidget(self.num_1, 2, 0, 1, 1)
        self.num_enter = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_enter.sizePolicy().hasHeightForWidth())
        self.num_enter.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(19)
        font.setBold(False)
        font.setWeight(50)
        self.num_enter.setFont(font)
        self.num_enter.setObjectName(_fromUtf8("num_enter"))
        self.gridLayout_2.addWidget(self.num_enter, 3, 2, 1, 1)
        self.num_0 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_0.sizePolicy().hasHeightForWidth())
        self.num_0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(45)
        font.setBold(False)
        font.setWeight(50)
        self.num_0.setFont(font)
        self.num_0.setObjectName(_fromUtf8("num_0"))
        self.gridLayout_2.addWidget(self.num_0, 3, 0, 1, 1)
        self.num_8 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_8.sizePolicy().hasHeightForWidth())
        self.num_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(45)
        font.setBold(False)
        font.setWeight(50)
        self.num_8.setFont(font)
        self.num_8.setObjectName(_fromUtf8("num_8"))
        self.gridLayout_2.addWidget(self.num_8, 0, 1, 1, 1)
        self.num_6 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_6.sizePolicy().hasHeightForWidth())
        self.num_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(45)
        font.setBold(False)
        font.setWeight(50)
        self.num_6.setFont(font)
        self.num_6.setObjectName(_fromUtf8("num_6"))
        self.gridLayout_2.addWidget(self.num_6, 1, 2, 1, 1)
        self.num_5 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_5.sizePolicy().hasHeightForWidth())
        self.num_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(45)
        font.setBold(False)
        font.setWeight(50)
        self.num_5.setFont(font)
        self.num_5.setObjectName(_fromUtf8("num_5"))
        self.gridLayout_2.addWidget(self.num_5, 1, 1, 1, 1)
        self.num_clear = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_clear.sizePolicy().hasHeightForWidth())
        self.num_clear.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(19)
        font.setBold(False)
        font.setWeight(50)
        self.num_clear.setFont(font)
        self.num_clear.setObjectName(_fromUtf8("num_clear"))
        self.gridLayout_2.addWidget(self.num_clear, 3, 1, 1, 1)
        self.num_7 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_7.sizePolicy().hasHeightForWidth())
        self.num_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(45)
        font.setBold(False)
        font.setWeight(50)
        self.num_7.setFont(font)
        self.num_7.setObjectName(_fromUtf8("num_7"))
        self.gridLayout_2.addWidget(self.num_7, 0, 0, 1, 1)

        self.retranslateUi(OcareGui)
        QtCore.QMetaObject.connectSlotsByName(OcareGui)

    def retranslateUi(self, OcareGui):
        OcareGui.setWindowTitle(_translate("OcareGui", "Form", None))
        self.label.setText(_translate("OcareGui", "Robot Stat", None))
        self.label_4.setText(_translate("OcareGui", "Orient", None))
        self.label_2.setText(_translate("OcareGui", "Arm Status", None))
        self.label_3.setText(_translate("OcareGui", "Diff Mode", None))
        self.pushButtonStart.setText(_translate("OcareGui", "Start", None))
        self.checkBoxArmOpen.setText(_translate("OcareGui", "Open", None))
        self.label_6.setText(_translate("OcareGui", "Diff Mode(NOW)", None))
        self.label_5.setText(_translate("OcareGui", "Robot Status", None))
        self.num_2.setText(_translate("OcareGui", "2", None))
        self.num_9.setText(_translate("OcareGui", "9", None))
        self.num_3.setText(_translate("OcareGui", "3", None))
        self.num_4.setText(_translate("OcareGui", "4", None))
        self.num_1.setText(_translate("OcareGui", "1", None))
        self.num_enter.setText(_translate("OcareGui", "ENTER", None))
        self.num_0.setText(_translate("OcareGui", "0", None))
        self.num_8.setText(_translate("OcareGui", "8", None))
        self.num_6.setText(_translate("OcareGui", "6", None))
        self.num_5.setText(_translate("OcareGui", "5", None))
        self.num_clear.setText(_translate("OcareGui", "CLEAR", None))
        self.num_7.setText(_translate("OcareGui", "7", None))

